* Emacs Plus

Emacs Plus is GNU Emacs formulae based on =emacs= [[https://github.com/Homebrew/homebrew-core/blob/master/Formula/emacs.rb][formulae]]. The difference is
that some of the options available from =emacs= formulae are enabled by default
in =emacs-plus= and some new [[#options][additional options]] are available for user.

** Install

#+BEGIN_SRC bash
$ brew tap d12frosted/emacs-plus
$ brew install emacs-plus [options]
#+END_SRC

By default (without any addition options) this formula install Cocoa version of
Emacs with support of =gnutls=, =imagemagick=, =librsvg=, =libxml2=, dynamic
modules and multicolor fonts and Spacemacs icon. Please see the list of
available options to disable any bit of default behaviour or add even more
stuff.

In order to install without Spacemacs icon you should use following command.

#+BEGIN_SRC bash
$ brew install emacs-plus --without-spacemacs-icon
#+END_SRC

** Options

To get list of all available options, call ~brew info emacs-plus~. Here is
relevant part from output of that command for your convenience.

#+BEGIN_SRC bash
==> Options
--with-ctags
	Don't remove the ctags executable that Emacs provides
--with-dbus
	Build with dbus support
--with-mailutils
	Build with mailutils support
--with-natural-title-bar
	Experimental: use a title bar colour inferred by your theme
--with-no-title-bars
	Experimental: build with a patch for no title bars on frames (--HEAD has this built-in via undecorated flag)
--with-x11
	Experimental: build with x11 support
--without-cocoa
	Build a non-Cocoa version of Emacs
--without-gnutls
	Build without gnutls support
--without-imagemagick@6
	Build without imagemagick@6 support
--without-librsvg
	Build without librsvg support
--without-libxml2
	Build without libxml2 support
--without-modules
	Build without dynamic modules support
--without-multicolor-fonts
	Build without a patch that enables multicolor font support
--without-spacemacs-icon
	Build without Spacemacs icon by Nasser Alshammari
--HEAD
	Install HEAD version
#+END_SRC

Note that by default =emacs-plus= is builds Cocoa version of Emacs with
=gnutls=, =imagemagick=, =librsvg= and dynamic modules support by default. Also
it changes default GNU Emacs icon to Spacemacs icon. If you wish to change
defaults, just use =--without-FEATURE= flag.

Note that =--HEAD= builds are not really supported. They may fail to install,
they may crash at run time. Or even worse, the may work as expected. So use this
option at your own risk. And feel free to open up issues you face, just remember
that I am not close enough to Emacs development process to provide you much help
with any arising issues.

** Known Issues

Please checkout [[https://github.com/d12frosted/homebrew-emacs-plus/issues?utf8=%E2%9C%93&q=is%253Aissue%2520][Issues]] page for a list of all known issues.

** Acknowledgements

Many thanks to [[https://github.com/d12frosted/homebrew-emacs-plus/graphs/contributors][all contributors]]. And everyone reporting issues!
