* Emacs Plus

Emacs Plus is GNU Emacs formulae based on =emacs= [[https://github.com/Homebrew/homebrew-core/blob/master/Formula/emacs.rb][formulae]]. The difference is
that some of the options available from =emacs= formulae are enabled by default
in =emacs-plus= and some new [[#options][additional options]] are available for user.

** Install

#+BEGIN_SRC bash
$ brew tap d12frosted/emacs-plus
$ brew install emacs-plus [options]
#+END_SRC

By default (without any addition options) this formula install Cocoa version of
Emacs with support of =gnutls=, =imagemagick=, =librsvg=, =libxml2= dynamic
modules and multicolor fonts and Spacemacs icon. Please see the list of
available options to disable any bit of default behaviour or add even more
stuff.

In order to install without Spacemacs icon you should use following command.

#+BEGIN_SRC bash
$ brew install emacs-plus --without-spacemacs-icon
#+END_SRC

** Options

To get list of all available options, call ~brew info emacs-plus~. Here is
relevant part from output of that command for your convenience.

#+BEGIN_SRC bash
==> Options
--with-ctags
	Don't remove the ctags executable that Emacs provides
--with-dbus
	Build with dbus support
--with-mailutils
	Build with mailutils support
--with-natural-title-bar
    Build with an inferred title bar colour (--HEAD is supported)
--with-no-title-bars
	Build with a patch for no title bars on frames (neither --HEAD nor --devel currently supported)
--with-x11
	Build with x11 support
--without-cocoa
	Build a non-Cocoa version of Emacs
--without-gnutls
	Build without gnutls support
--without-imagemagick
	Build without imagemagick support
--without-librsvg
	Build without librsvg support
--without-libxml2
	Build without libxml2 support
--without-modules
	Build without dynamic modules support
--without-multicolor-fonts
	Build without a patch that enables multicolor font support
--without-spacemacs-icon
	Build without Spacemacs icon by Nasser Alshammari
--devel
	Install development version 25.1.90
--HEAD
	Install HEAD version
#+END_SRC

Note that by default =emacs-plus= is builds Cocoa version of Emacs with
=gnutls=, =imagemagick=, =librsvg= and dynamic modules support by default. Also
it changes default GNU Emacs icon to Spacemacs icon. If you wish to change
defaults, just use =--without-FEATURE= flag.

** Known Issues

*** Crash on start with error about =imagemagick=
In case Emacs crashes right after the start with an error about =imagemagick=
dynamic library, you have to reinstall =emacs-plus=. Sorry for the
inconvenience.

In order to reinstall just use following commands.

#+BEGIN_SRC bash
$ brew uninstall emacs-plus
$ brew install emacs-plus [options]
#+END_SRC

The exact error that hints you to reinstall is following error.

#+BEGIN_SRC
Dyld Error Message:
  Library not loaded: /usr/local/opt/imagemagick/lib/libMagickWand-6.Q16.2.dylib
  Referenced from: /usr/local/Cellar/emacs-plus/25.1/Emacs.app/Contents/MacOS/Emacs
  Reason: image not found
#+END_SRC
